### ISSUE TITLE
Code for Arduino uno

### ISSUE THREAD

**Issue by paula75** [engkan2kit/ADE7758#2]
Hi!

I'm trying to test it for an Arduino UNO, this is for an Arduino MEGA, is this correct?

Regards!

**Comment by engkan2kit** [comment]
We used both mega and uno in this project. However, this is incomplete. Most functions have been tested though. I tested this for SPI and software SPI. I had to use software SPI since my application that time used the SPI for my trasnceiver and has a different SPI mode and reseting the mode adds delay to the comms. I can help you but I am busy until next week. Maybe you can contact me on facebook so I can answer more of your questions. engkan2kit@gmail.com

**Comment by engkan2kit** [comment]
I updated the source code so that you can use the SPI from arduino. You can check the demo on how to use it. The SPI is passed by reference. In the example it is using an instance of SPIClass created from the SPI.h. You can use any arduino now.

Please note the I was not able to test this because I don't have the hardware anymore. In any case, do you have a schematic of you circuit so I can check the connections?

**Comment by paula75** [comment]
![squematic](https://cloud.githubusercontent.com/assets/22896228/26453164/d053e708-4130-11e7-9be5-441bdfc36336.png)

Hi!, thanks for your answer, so far i have the shown connection. I am not sure about if i have to connect APCF, VAPCF and IRQ.

**Comment by engkan2kit** [comment]
You can connect the IRQ to any IO interrupt or pin change interrupt, in this code, I removed the interrupt since it can be used with it. APCF and VAPCF are for calibration. I did not use it also and resorted to software calibration via Least Squares regression.

**Comment by engkan2kit** [comment]
You can connect the IRQ to any IO interrupt or pin change interrupt, in this code, I removed the interrupt since it can be used with it. APCF and VAPCF are for calibration. I did not use it also and resorted to software calibration via Least Squares regression.

**Comment by paula75** [comment]
Ok, i think that i will calibrate de measument via software instead. Thank you very much for the help

Regards!
