### ISSUE TITLE
CALIBRATION PROBLEM 

### ISSUE THREAD

**Issue by kumareshkc** [engkan2kit/ADE7758#3]
Hello,

I have installed your library and I am using the ADE7758 IC as mentioned in your schematic. The code is working fine and providing the output in the serial monitor. I can see that we are getting the output in the form of HEXADECIMAL values. How should i convert it into proper values like  230.4 v , 1.58 A  etc. ?   please guide me to extract the same values from your sketch. Is there any calibration required to get my desired value ?

**Comment by engkan2kit** [comment]
Hi, 
If you used the sample code, the data are displayed in HEX because the Serial.println(myADE.getWattHR(PHASE_A), HEX) function displays it in HEX. You can convert the hex to float by multiplying your scaling factor and offset. By the way, you can display it to decimal but still the value is not 230V etc. This is just the digital representation of what the ADE7758 reads. You will need to sample some values first (calibration process). This depends on the resistor values you used and the sensor accuracy/precision. So what I did in my application before is that I sampled at known voltages and currents and record the equivalent digital value.

Here is how I did it:
1. Try providing multiple AC voltage levels. In my case, I used a computer Auto voltage regulator(AVR) which has 110V output, 220V output, our power outlet is around 230V.
2. I started with 0V AC, the checked the VRM digital value (dec or hex) and recorded it in excel
    Then, 110V AC (use a good multimeter to get the exact voltage) and check the corresponding VRMS digital and recorded it. and do the same for the other voltage level.
3. Once you get all the data pairs, you can do a scatter plot in excel, add a trendline and select linear model. this will give you the linear formula in the form of y=mx+b where y is the actual voltage, m is the scaling factor, x is the digital voltage reading, and b is the offset. In short you will do a linear regression to get the formula for conversion.
    Just take note of the byte sizes that were given in the ADE7758 datasheet. For example, AVRMS register or the Phase A VRMS, is 24 bits (3 bytes) Signed register. Meaning it will have a value of -2^23 to positive (2^23)-1. In my library, since there is no 24 bit datatype, I stored it in a long integer datatype which is 32 bits. I just sign extended the 24 bit so carry the sign in the 32 bit value. But since this is C/C++ the HEX value will just display the hexadecimal equivalent of the 32 bit long value.

4. for the current calibration, I attached  different types of load. For example 50W light bulb, 100W light bulb, 1000W flat iron, etc. its up to you. just make sure you have a good ammeter that can read the actual current. Then do the same steps with the voltage and do a linear regression to get the formula.

5. for the power reading calibration, you may use a wattmeter, but you can just settle with an ammeter and voltmeter combination for the power. Again do the same with the above steps to get the conversion formula.

**Comment by kumareshkc** [comment]
Hello, 
Thank you for your timely help. I will try to implement the above mentioned steps into my code to get the proper value.  if i have any doubt in this process i will ask you. please guide me through this process. if you find any sample excel file please provide me that for the reference.

**Comment by gusagar** [comment]
Saludo, estas activo?
